version: '3.3'

services:

  picontrolpanel:
    image: rembert/pi-control-panel:dev
    container_name: picontrolpanel
    build:
      context: ../.
      dockerfile: Docker/Dockerfile.pi64
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - '8081:8080'
    volumes:
      - '/boot/:/boot/:ro'
      - '/bin/:/bin/:ro'
      - '/etc/ssh/sshd_config:/etc/ssh/sshd_config:ro'
      - '/etc/sudoers:/etc/sudoers:ro'
      - '/lib/:/lib/:ro'
      - '/proc/:/proc/:ro'
      - '/sbin/:/sbin/:ro'
      - '/usr/bin/:/usr/bin/:ro'
      - '/usr/lib/:/usr/lib/:ro'
