version: '3.7'

services:

  picontrolpanel:
    image: rembert/pi-control-panel:latest-amd64
    container_name: picontrolpanel
    environment:
      - TZ=America/Toronto
    ports:
      - '8081:8080'
    volumes:
      - '/boot/:/boot/:ro'
      - '/bin/:/bin/:ro'
      - '/etc/ssh/sshd_config:/etc/ssh/sshd_config:ro'
      - '/etc/sudoers:/etc/sudoers:ro'
      - '/lib/:/lib/:ro'
      - '/proc/:/proc/:ro'
      - '/sbin/:/sbin/:ro'
      - '/usr/bin/:/usr/bin/:ro'
      - '/usr/lib/:/usr/lib/:ro'

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: --no-auth
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - 'portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  portainer_data:
